language: python

python:
  - "3.7"

install: 
  - pip install -r requirements.txt
  - pip install black pylint pylint-exit

script:
  - black --check -t py37 .
  - pylint --output-format=text *.py app || pylint-exit $?
